Html file customization
BloomTech-Labs/coder-heroes-fe pull request #138
Opened 2022-02-04 18:13 UTC by RoseGabriely

## Description

Our website's tab was styled with the default title and icon that came with the HTML file. I changed the title to "CoderHeros" and updated the logo to the CoderHeros logo from our figma document.

## Loom Video

[Loom Video](https://www.loom.com/share/a295afdd4e5d408e829ad36d961d988c)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-02-04 18:28 UTC, ElchinNasirov approved these changes
Quick but important changes. Well done.

2022-02-04 21:00 UTC, seanmp3 requested changes
Good meta data update, its nice seeing how much simple things adds to the look of the website

2022-02-04 21:16 UTC, RoseGabriely commented on public/index.html
> +  <title>CoderHeros</title>
Great catch! Fixed!

2022-02-06 09:35 UTC, seanmp3 approved these changes
Perfectly done, thanks Rose for all your work as a tpm this unit

2022-02-09 19:38 UTC, manny-glez commented
Well done, its looks better already.

2022-02-09 19:41 UTC, manny-glez approved these changes
Well done, its looks better already.

2022-02-11 04:24 UTC, merged