Feature/instructor add course validation yup
BloomTech-Labs/coder-heroes-fe pull request #181
Opened 2022-04-12 03:01 UTC by Raj-04

## Description
Done some validations for the add-course form

Fixes # (issue)

## Loom Video

Please paste a link here to a quick loom video walking through what you did in your PR.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

2022-04-12 04:25 UTC, jmerz826 requested changes
Overall nice job, Raj. Few naming convention inconsistencies and a small spelling error are the only outstanding issues I see.

2022-04-12 04:25 UTC, jmerz826 commented on src/components/pages/InstructorAddCourse/InstructorAddCourseFormSchema.js
> +    .min(7, 'must be older than 7')
good, much more descriptive. Previously was unnecessarily ambiguous.

2022-04-12 04:25 UTC, jmerz826 commented on src/components/pages/InstructorAddCourse/InstructorAddCourseFormSchema.js
> +        'Wednasday',
```suggestion
        'Wednesday',
```

2022-04-12 04:25 UTC, jmerz826 commented on src/components/pages/InstructorAddCourse/InstructorAddCourseFormSchema.js
> +        'Wednasday',
Wednesday.. always the trickiest day of the week to spell

2022-04-12 04:25 UTC, jmerz826 commented on src/components/pages/InstructorAddCourse/InstructorAddCourseFormSchema.js
> +    .min(5, 'Too Short! Has to be More than 5 words')
```suggestion
    .min(5, 'Too Short! Has to be More than 5 characters')
```

2022-04-12 04:25 UTC, jmerz826 commented on src/components/pages/InstructorAddCourse/InstructorAddCourseFormSchema.js
> +    .max(50, 'Too Long! Has to be less than 50 words')
```suggestion
    .max(50, 'Too Long! Has to be less than 50 characters')
```

2022-04-12 04:25 UTC, jmerz826 commented on src/components/pages/InstructorAddCourse/InstructorAddCourseFormSchema.js
> +    .typeError('Must select a course')
```suggestion
    .typeError('Must select a program')
```

2022-04-12 04:25 UTC, jmerz826 commented on src/components/pages/InstructorAddCourse/InstructorAddCourseFormSchema.js
> +      'Please select a Course'
```suggestion
      'Please select a Program'
```

2022-04-13 15:26 UTC, sagun1151 approved these changes

2022-04-13 15:26 UTC, sagun1151 commented on src/components/pages/InstructorAddCourse/InstructorAddCourseFormSchema.js
>  });
Great use of yup validation think it covers all aspects of add course form

2022-04-13 16:14 UTC, ElchinNasirov approved these changes

2022-04-13 18:43 UTC, jmerz826 approved these changes

2022-04-14 22:35 UTC, Adamh1990 approved these changes

2022-04-18 08:35 UTC, merged