Feature/instructor dashboard
BloomTech-Labs/coder-heroes-fe pull request #184
Opened 2022-04-13 23:17 UTC by Adamh1990

## Description

Added the Instructor Dashboard (/instructor-dashboard) page to the app going off the Figma design, used dummy data for the instructor name, plugged in the sidebar and some dummy stats for the statistics display. More to work on here, this pr brings the page into existence and avoids one huge push in the future :)

## Loom Video

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-04-14 01:05 UTC, aaronpear approved these changes
As a partial pull request, I like the bits of comments to point where and what future code should be built in the future. Overall, looks clean and is a nice starting point moving forward. Good job!

2022-04-14 18:02 UTC, JakeHappel approved these changes
Good clean code I like the comments for future code.

2022-04-18 08:39 UTC, paulstgermain requested changes
Nice work with this PR, but this does need a Loom video walking us through the changes made!

Let me know when you've added one and I'll circle back to this PR!

2022-04-19 19:40 UTC, paulstgermain approved these changes

2022-04-19 19:40 UTC, merged