Feature/redux search instructors
BloomTech-Labs/coder-heroes-fe pull request #215
Opened 2022-04-28 19:22 UTC by JorgeEvangelista500

## Description

Connected Search instructors  to redux and the back end, users can now search through existing instructors.

## Loom Video

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-04-30 04:45 UTC, brandon-bee approved these changes
Overall really clean and readable code. Left the one comment where I saw a button could be switched with the Ant Design component, but that was the only thing I saw. Nice work!

2022-04-30 14:24 UTC, JorgeEvangelista500 commented on src/components/pages/LandingInstructor/SearchInstructors.js
> +                <button
That sounds like a good idea!, i kept the same design, i just added the on Click function

2022-05-03 00:07 UTC, Berenika14 approved these changes
Thanks for removing empty brackets and also the unneeded consoles. Might need a Loom video in order to be merged. Overall Great Job Jorge the code looks clean and readable.

2022-05-03 00:07 UTC, Berenika14 commented on src/components/pages/LandingInstructor/SearchInstructors.js
> -                  {' '}
Thanks for removing empty brackets and also the unneeded consoles.

2022-05-03 06:36 UTC, paulstgermain requested changes
This PR needs a Loom video before I can merge it! 😱 

Please add one as soon as you can!

2022-05-03 21:13 UTC, aamay022 approved these changes
Great work on implementing instructor reducer and actions to be able to view all instructors. Nice clean up on the console logs as well.

2022-05-03 21:33 UTC, bugsbrog approved these changes
Ooh, snazzy how you’re using Okta authentication in the SearchInstructors component! And nice work on making the button clickable! Ooh, love the dummy data (I think it's easier to work with actual data, whether it be dummy data or not 😆). I'd say get rid of the commented-out code in instructorActions.js (nice job on getting rid of "rogue console.logs"). Overall, GREAT work so far!

2022-05-04 23:11 UTC, paulstgermain approved these changes

2022-05-04 23:44 UTC, merged