Bug/programs landing page layout
BloomTech-Labs/coder-heroes-fe pull request #236
Opened 2022-05-19 19:25 UTC by jimjamesjimathy

## Description

We started by using the flexbox method to give an even amount of space to the left and right sides of all Programs components as well as resizing, aligning and adding correct fonts to all rendered text on the page. In some cases, the height of the element also needed adjustment to display the content correctly, so we also adjusted each element accordingly.

Fixes # ( Over-lapping text and un-centered images on page )

## Loom Video

https://www.loom.com/share/daeff8089c34490ca4c9effcd0c8e8eb

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-05-20 19:27 UTC, dstrazzeri commented on src/components/pages/LandingPrograms/CoderSitters.js
> +              <Text className="pl__na__sitter__text__container">
In PR reviews Edd mentioned there are ways to get around using explicit <br/> tags by using relative units for sizing within text containers.

2022-05-20 19:36 UTC, dstrazzeri approved these changes
Overall, super solid PR. I really appreciate your use of descriptive commit messages. And great use of flexbox, the layout is a huge improvement.

2022-05-20 19:40 UTC, dstrazzeri commented on src/styles/LandingPageStyles/index.less
>    font-family: 'Montserrat', cursive !important;
Paul & Edd also mentioned trying to stay away from using !important tags, so this is something as a team we should look into and discuss as I know it also used on previously written code.

2022-05-27 16:49 UTC, paulstgermain requested changes
This PR is looking great - the results speak for themselves, and for the most part the code you've written or touched on is formatted to match our current expectations!

That said, there are a couple things I'd love you to address before we merge this thing up - see the comments below for details!

2022-05-27 16:49 UTC, paulstgermain commented on src/components/pages/LandingPrograms/CoderYoga.js
> +                CODER-YOGA
Is Coder-Yoga presented this way in our docs, or should it be 2 separate words? 🤔

2022-05-27 16:49 UTC, paulstgermain commented on src/components/pages/LandingPrograms/CoderYoga.js
> +                CODER-YOGA
@dstrazzeri mentioned in a meeting just now that our docs refer to it as "CoderYoga" - maybe we should make this change before merging this code up!

2022-05-27 16:49 UTC, paulstgermain commented on src/styles/LandingPageStyles/index.less
> +  // background-color: #000;
Let's remove this commented-out code if it isn't necessary!

2022-05-31 21:21 UTC, paulstgermain approved these changes

2022-05-31 21:22 UTC, merged