Built out resources component based on Student Figma Deisgn flow
BloomTech-Labs/coder-heroes-fe pull request #270
Opened 2022-06-23 13:47 UTC by leewp8

Co-authored-by: Spencer Longhurst spencersean12@gmail.com
Co-authored-by: Ahmad Wahidy shah.wahidy@gmail.com
Co-authored-by: Jose Mercado josefmercado99@gmail.com

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Loom Video

<div style="position: relative; padding-bottom: 56.25%; height: 0;"><iframe src="https://www.loom.com/embed/a6b60db045194045977919426e581443" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe></div>

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-06-23 16:20 UTC, kylerostler submitted a review, later dismissed
Looks good could use more styling overall but the skeleton is there. Set up nicely so that it can be connected to redux and styled in the future. Clean code no unecessary comments or console.logs.

2022-06-23 22:47 UTC, Ogden-R approved these changes
i love that you were able to make cards and components for those. these components look very nice and now just need a little bit of love connecting them to the instructors stuff. great job!

2022-06-27 16:11 UTC, ashtilawat23 requested changes
Looks like you deleted the entire package-lock. We don't want to delete it but preserve the one on Main. I would open your branch in VScode. Open the raw text from the package-lock in the browser. Use Cmd A to select all, Cmd C to copy, and Cmd V to paste into your branch. If you are on PC, it's Control.

2022-06-27 18:08 UTC, brandib222 approved these changes
Great start on the student resources page! Good use of antd to keep things simple and make things easier to style/ make dynamic in the future.

2022-06-28 22:12 UTC, Michael-Subbarao approved these changes
Overall it looks like a great start to the component and everything looks well designed. Code looks clean as well. I might make the StudentResources component slightly more modular but that can be done when it gets hooked up to the backend.

2022-06-28 22:12 UTC, Michael-Subbarao commented on src/components/pages/StudentHome/StudentResources.js
> +          <Card className="resourceCard">
I would suggest separating this card out into it's own component for reuse.

2022-07-11 21:55 UTC, anastasia-lapteva approved these changes
Hello William, Spencer, Ahmad, and Jose,

Thank you for thoroughly walking us through all relevant information from the Jira Kanban board, to the Figma design, to the code, to your local deployment. I find that getting started drawing something on the blank screen is often the most difficult part...good job with this!

2022-07-21 18:00 UTC, laurensruiz commented
The basic structure of the page looks great and might need more styling but the overall code looks clean.

2022-07-22 02:33 UTC, wreck888 submitted a review, later dismissed
I would recommend not hardcoding the data but instead making seed files for them in the backend. Other than that the code looks great!

2022-07-22 20:54 UTC, EmmS21 approved these changes
Great start building out the component, code looks pretty clean

2022-07-28 18:01 UTC, laurensruiz submitted a review, later dismissed
The basic structure of the page looks great and might need more styling. Antd design components is a bit hard to style at first, but once you get a good grasp of it, it'll be easier. Great work!

2022-07-29 00:05 UTC, merged