removed the Eslint error by Eslint disabl
BloomTech-Labs/coder-heroes-fe pull request #71
Opened 2021-12-03 18:54 UTC by ehsan2793

"eslint-disable-next-line" was added to the code to remove the ESlint error "unused variables."
Since we don't know if we will use these variables in the future, we are only skipping over the code, and the overall code has not changed.

As we find more about our code and the variables needed to meet the MVP, we can use or altogether remove the unused variables.  

loom https://www.loom.com/share/f5c8df75a6e84855830280d54fc7d0fc

2021-12-03 19:38 UTC, stevenjhomem reviewed
Looks good to me! It also looks like you fixed the "submitting your entire package" issue from earlier.

2021-12-04 01:52 UTC, TraNequaFauntleroy commented
Looks good to me!

2021-12-06 15:15 UTC, Pauline122112 reviewed
Overall, looks good! great job! I especially like the loom video which gives an in-depth analysis.

2021-12-06 15:15 UTC, Pauline122112 commented on src/components/pages/ParentBooking/AvailableCourses.js
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Good to see that you disabled eslint and made a comment about it on line 15.

2021-12-06 16:13 UTC, stevenjhomem requested changes
Good job disabling here!

It looks like there are others that need to be disabled still at the bottom of this page
<img width="571" alt="Screen Shot 2021-12-06 at 10 13 46 AM" src="https://user-images.githubusercontent.com/83235906/144881411-2b7e664d-bc13-48cd-ae27-6e17c38eed94.png">
.

2021-12-06 16:24 UTC, vannguyen141290 commented
Those error messages can be very annoying for coder. good that you disabled them by using eslint. good work!

2021-12-10 19:32 UTC, zach-morris-txt commented
Because using ESLint disabler was actually against DRY standards, we will have to return to this PR and handle the linting issues appropriately. We can handle the additional errors Stephen found here [ https://github.com/BloomTech-Labs/coder-heroes-fe/pull/71#pullrequestreview-824160153 ] as well

2021-12-10 19:45 UTC, ehsan2793 commented
yeah I'm going to close this pull request

2021-12-10 19:46 UTC, closed without merging