modified data structure for parent bookings and built tabs feature
BloomTech-Labs/coder-heroes-fe pull request #80
Opened 2021-12-10 12:32 UTC by vannguyen141290

After working with @ehsan2793 to determined data structure, I use dummyData based on that to complete the parents' booking lists. The API endpoint is not working for some reason, but the target data structure is decided so I went ahead and build basic functionalities so that UX engineer can start working on it.

Loom [https://www.loom.com/share/3cf86e683c254d8394fe5965c05ffb12](url}

2021-12-10 14:14 UTC, Brendonjhawkins approved these changes
Great work Thi!

2021-12-10 15:51 UTC, TraNequaFauntleroy reviewed
Great job fixing the functionality of the Parent booking card and cleaning up the index.js. Also, I cannot wait to get my design hands on this!

2021-12-10 16:20 UTC, ehsan2793 approved these changes
Good job on using dummy data. We will figure out the live sever issue soon. Overall great job

2021-12-10 16:20 UTC, ehsan2793 commented on src/components/pages/ParentBooking/ParentBookingContainer.js
> +  const renderTab = key => {
Excellent work, very clean, and I love this function more than anything. It's brilliant.

2021-12-10 16:52 UTC, ryan-hamblin commented on src/components/pages/ParentBooking/ParentBookingCard.js
> +const ParentBookingCard = ({ booking }) => {
If you need to use the props' values you could destructure 'booking' here between these lines. 

ex: 

``` const { subject, title, ... etc} = {...booking}; ```

2021-12-10 16:53 UTC, ryan-hamblin commented on src/components/pages/ParentBooking/ParentBookingCard.js
> +        {/* <div className="buttonWrapper">
Please delete unused or commented-out code.

2021-12-10 16:54 UTC, ryan-hamblin commented on src/components/pages/ParentBooking/ParentBookingContainer.js
> +/* eslint-disable react-hooks/exhaustive-deps */
Please don't disable the linter.

2021-12-10 16:55 UTC, ryan-hamblin commented on src/components/pages/ParentBooking/ParentBookingContainer.js
> +    // when the component mounts, trigger action fetchParentBookings to get the list of bookings
I love code comments!

2021-12-10 16:55 UTC, ryan-hamblin commented on src/components/pages/ParentBooking/ParentBookingContainer.js
> +    // props.fetchParentBookings();
This is commented out code and we need to remove it.

2021-12-10 16:58 UTC, ryan-hamblin commented on src/components/pages/ParentBooking/index.js
> +        {/* not sure if this is still needed */}
Let's remove :)

2021-12-10 16:59 UTC, ryan-hamblin commented on src/components/pages/ParentHome/index.js
> +  // useEffect(() => {
If we don't need it, let's delete it.

2021-12-10 16:59 UTC, ryan-hamblin commented on src/components/pages/ParentHome/index.js
> +  console.log('calendar renders');
Please remove this console.log

2021-12-10 17:00 UTC, ryan-hamblin commented on src/redux/reducers/parentReducer.js
> +    bookings: [
Not totally necessary but if you want to reduce the size of lines inside this reducer you could define this dummy data elsewhere and import in.

2021-12-10 17:08 UTC, ryan-hamblin commented on src/components/pages/ParentHome/index.js
>      console.log(collapsed);
Please remove this console.log()

2021-12-10 17:10 UTC, ryan-hamblin submitted a review, later dismissed
Wow! You accomplished a lot here and did great work especially in the instance where you're unblocking some of your teammates. 

I'd love for you to clean up the .logs and commented out code including the disable eslint rules lines. 

Also, great work on the tabs feature, but there is no description or supporting documentation as to 'why'that feature was delivered in congruency w/ the data model cleanup.

2021-12-17 21:23 UTC, zach-morris-txt requested changes
Needs 'merge conflicts' resolved. I will have them cleared by late evening tonight.

2021-12-20 01:12 UTC, zach-morris-txt approved these changes
Excellent job! Very consistent methodology...
I've pulled from main and handled the Merge Conflicts. This branch is ready to be merged.

2021-12-22 16:57 UTC, merged