Feature nav
BloomTech-Labs/coder-heroes-fe pull request #85
Opened 2021-12-15 01:46 UTC by TraNequaFauntleroy

I added

2021-12-15 20:32 UTC, stevenjhomem approved these changes
Great! We really needed a styled nav bar :)

2021-12-16 19:18 UTC, zach-morris-txt commented on src/styles/ParentStyles/index.less
> -
You write and maintain clean code, this is a great example

2021-12-16 19:24 UTC, zach-morris-txt requested changes
You have an eye for aestheticism and organization. I looked through the Sider you added. That piece cleaned up the mess that was the Menu/keys/default keys/etc. It's much better for it. Your commit messages are also fantastic. 

This was an accidental PR from what I understand -you have more in mind to complete it and you plan on making a [LOOM] video walkthrough- so I'll leave a "requests changes" review.

2021-12-17 16:46 UTC, ryan-hamblin reviewed
Keep up the good work, are a few minor formatting issues in your styles. Other than that keep working out this feature!

2021-12-17 16:46 UTC, ryan-hamblin commented on src/styles/global.less
> +        background-color: rgba(0, 201, 183, 0.8);
Remove an indent here. Keep your properties on your css Objects aligned.

2021-12-22 18:08 UTC, merged