Feature/instructor logout button+function
BloomTech-Labs/coder-heroes-fe pull request #99
Opened 2022-01-13 21:34 UTC by pjaepole

- imported ExportOutlined from @ant-design/icons, imported { Link } from react-router-dom

>importing Header.js in index.js file to see if the prebuilt logout function works or not
after testing it was working so I will move over the function to the logout button on instructor and parent logout
removed index.js changes to revert back to original

- InstructorSidebar.js 
import { useOktaAuth } from '@okta/okta-react';
const { authService } = useOktaAuth();

- added onclick function to the logout menuItem to log out when clicked
does remove token from localstorage and it redirect user to login page!

- removed a modified file from a pull request, parentsidebar.js which does not have anything to do with this pull request

2022-01-13 22:39 UTC, alextcedwards requested changes
Good job separating the pull requests! couple things: 

Think you forgot to include video recording to explain what you did. 

Updating craco to different version will cause merge conflicts with everyone since no one else updated, so I would change that back to original.

The rest looks pretty good though!

2022-01-14 00:52 UTC, Ryan-E-Mark commented
Looks great, good work referencing the Okta documentation to successfully implement the removal of the JWT from localstorage.

2022-01-14 01:47 UTC, pjaepole commented on src/components/pages/InstructorHome/InstructorSidebar.js
> +            <Link to="/logout">Logout</Link>
it seems like okta authService.logout automatically redirects the user to the login page after logging out.
But I agree that it is a better idea to change it to landing page.
I changed it to <Link to='/landing'> and I think I missed this on other PR as well so I will change that as well

2022-01-14 17:29 UTC, Ryan-E-Mark commented on src/components/pages/InstructorHome/InstructorSidebar.js
> +            <Link to="/logout">Logout</Link>
Ahh ok. Well either way good job on this pull request! We can work through the okta stuff a bit more once Ryan gets back.

2022-01-20 05:42 UTC, merged